workflows:
  test: 
    name: Build
    environment:
      groups:
        - Xcode
      xcode: $XCODE_VERSION
    triggering:
      events:
        - push
        - pull_request
      branch_patterns:
        - pattern: develop
          include: true
          source: true
        - pattern: develop
          include: true
          source: false
      cancel_previous_builds: true
    scripts:
      - name: Build
        script: xcodebuild build \
          -scheme "$XCODE_SCHEME" \
          -destination 'platform=iOS Simulator,name=iPhone 14 Pro,OS=17.0'
